# Generated by Django 5.2.8 on 2026-03-01 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_no', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='团号')),
                ('agency', models.CharField(blank=True, max_length=128, verbose_name='地接社')),
                ('hotel', models.CharField(blank=True, max_length=128, verbose_name='酒店')),
                ('region', models.CharField(blank=True, max_length=64, verbose_name='地区')),
                ('people_count', models.PositiveIntegerField(default=0, verbose_name='人数')),
                ('feedback_count', models.PositiveIntegerField(default=0, verbose_name='意见表回收数量')),
                ('feedback_rate', models.CharField(blank=True, max_length=32, verbose_name='回收率')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
            ],
            options={
                'verbose_name': '团',
                'verbose_name_plural': '团',
                'db_table': 'questionnaire_group',
            },
        ),
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_language', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='地陪语言和讲解')),
                ('guide_service', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='地陪服务态度')),
                ('vehicle_comfort', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='车辆舒适度')),
                ('vehicle_clean', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='车辆干净程度')),
                ('driver_service', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='司机服务')),
                ('food_quality', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='餐饮质量')),
                ('restaurant_environment', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='餐厅环境')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travelers', to='main_app.group')),
            ],
            options={
                'verbose_name': '旅客问卷',
                'verbose_name_plural': '旅客问卷',
                'db_table': 'questionnaire_traveler',
            },
        ),
    ]
