# Generated by Django 5.2.8 on 2026-03-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullEscort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pace', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='节奏')),
                ('explanation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='讲解')),
                ('service', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='服务')),
                ('design', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='设计')),
                ('expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='期望')),
                ('recommendation', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='推荐')),
                ('overall', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='总评')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_escorts', to='main_app.group')),
            ],
            options={
                'verbose_name': '全陪问卷',
                'verbose_name_plural': '全陪问卷',
                'db_table': 'questionnaire_full_escort',
            },
        ),
    ]
