# Generated by Django 5.2.8 on 2026-03-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_fullescort'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullescort',
            name='agency',
            field=models.CharField(blank=True, max_length=128, verbose_name='地接社'),
        ),
        migrations.AddField(
            model_name='fullescort',
            name='hotel',
            field=models.CharField(blank=True, max_length=128, verbose_name='酒店'),
        ),
        migrations.AddField(
            model_name='fullescort',
            name='region',
            field=models.CharField(blank=True, max_length=64, verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='agency',
            field=models.CharField(blank=True, max_length=128, verbose_name='地接社'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='hotel',
            field=models.CharField(blank=True, max_length=128, verbose_name='酒店'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='region',
            field=models.CharField(blank=True, max_length=64, verbose_name='地区'),
        ),
    ]
