# Generated by Django 5.2.8 on 2026-03-09

from django.db import migrations, models


def fill_group_date_from_end_date(apps, schema_editor):
    Group = apps.get_model('main_app', 'Group')
    for g in Group.objects.all():
        if getattr(g, 'end_date', None):
            g.date = g.end_date.strftime('%Y-%m')
            g.save(update_fields=['date'])


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_fullescort_agency_fullescort_hotel_fullescort_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.CharField(blank=True, max_length=7, verbose_name='日期(YYYY-MM)'),
        ),
        migrations.RunPython(fill_group_date_from_end_date, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='group',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='group',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='group',
            name='region',
        ),
        migrations.RemoveField(
            model_name='group',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='group',
            name='end_date',
        ),
    ]
