# Generated by Django 6.0.2 on 2026-03-09 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_group_date_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='fullescort',
            name='guide',
            field=models.CharField(blank=True, max_length=128, verbose_name='导游'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='guide',
            field=models.CharField(blank=True, max_length=128, verbose_name='导游'),
        ),
    ]
