# Generated by Django 6.0.2 on 2026-03-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_fullescort_guide_traveler_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='名字')),
                ('region', models.CharField(blank=True, max_length=64, verbose_name='地区')),
            ],
            options={
                'verbose_name': '地接社供应商',
                'verbose_name_plural': '地接社供应商',
                'db_table': 'supplier_agency',
            },
        ),
        migrations.CreateModel(
            name='SupplierGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_type', models.CharField(choices=[('local', '地陪'), ('full', '全陪')], default='local', max_length=16, verbose_name='类型')),
                ('name_cn', models.CharField(db_index=True, max_length=128, verbose_name='中文名')),
                ('name_en', models.CharField(blank=True, max_length=128, verbose_name='英文名')),
                ('language', models.CharField(blank=True, max_length=128, verbose_name='语种')),
                ('region', models.CharField(blank=True, max_length=64, verbose_name='地区')),
            ],
            options={
                'verbose_name': '导游供应商',
                'verbose_name_plural': '导游供应商',
                'db_table': 'supplier_guide',
            },
        ),
    ]
